#Leitura de chave inexistente
READ [c1]
#Criação e escrita de 2 chaves
READ [c1]
WRITE [(c1,v1)(chave2,valor-exemplo)]
#Leitura de chave existente
#Escrita de uma chave nova e outra existente
WRITE [(chave2,valor-exemplo2)(umaChave,umValor)]
# backup
BACKUP
# Eliminação de chave existente e de chave não existente
DELETE [c1,chaveAleatoria]
#WAIT 1000
SHOW
#BACKUP
#BACKUP
BACKUP
BACKUP
READ [c1]
READ [c1]
