#Leitura de chave inexistente
READ [c1]
#Criação e escrita de 2 chaves
WRITE [(c1,v1)(chave2,valor-exemplo)(chave3,valor-exemplo3)(a2,valor4)]
#Leitura de chave existente
READ [chave2]
#Escrita de uma chave nova e outra existente
WRITE [(chave2,valor-exemplo2)(umaChave,umValor)]
#backup
BACKUP
# Eliminação de chave existente e de chave não existente
DELETE [c1,chaveAleatoria]
WRITE [(cbhave2,valor-exemplo2)(umaChave,umValor)]
DELETE [c1,chaveAleatoria]
WRITE [(cave2,valor-exemplo2)(umaChave,umValor)]
DELETE [umaChave]
BACKUP